### ISSUE TITLE
Uncap cutscenes feature seems to be broken in 1.03

### ISSUE THREAD

**Issue by soundsofsilence** [Lyall/IshinFix#12]
I've just started the game, and the opening cinematic, which isn't prerendered (?) is still capped at 30 FPS.

**Comment by Lyall** [comment]
The very first cutscene that you see in the game (a rainy night scene with samurai), is pre-rendered so there's not much that can be done about that. Unless you are referring to another cutscene? Perhaps try the fourth cutscene from Chapter 1 in the Replay theater. The first 3 cutscenes in chapter 1 are pre-rendered.

**Comment by soundsofsilence** [comment]
A thousand pardons, I accidentally disabled [Remove Cutscene FPS Cap] and forgot to reenable it. I'm an idiot🤦. Everything works as intended!
