### ISSUE TITLE
1.06 patch broke IshinFix

### ISSUE THREAD

**Issue by helichoppa** [Lyall/IshinFix#14]
Hi,

The latest update - patch 1.06 - broke IshinFix. The game will crash during the warning intro screen. I removed IshinFix and the game booted up fine again.

**Comment by Lyall** [comment]
Can confirm that I'm getting that crashing too on 1.06. It doesn't actually appear to be an issue with IshinFix but rather with the ASI loader. If you delete IshinFix.asi, you'll still get crashing on startup. I'll need to look in to this further.

**Comment by Lyall** [comment]
Okay looks like adding `winmm.ini` with these contents will fix the crashing. I'll add this file to the latest release.
```ini 
[GlobalSets]
DontLoadFromDllMain=0 
```

**Comment by helichoppa** [comment]
Yup, the game boots up fine now. Thanks for the quick fix!

**Comment by JohnFullsauce** [comment]
Downloading the latest release worked for me! Thank you!
