### ISSUE TITLE
Compatibility with Gamepass version

### ISSUE THREAD

**Issue by rpontes343** [Lyall/IshinFix#16]
Hi, is there any plan on update this fix with the gamepass version since it doesnt have the Win64 folder? Instead the GP version uses a WinGDK folder.

**Comment by Lyall** [comment]
It should theoretically work fine on the gamepass version unless it's different than the MS store version. I added support for it a while back at somebody's request. Have you tried extracting it to the WinGDK folder and running the game? If so can you post the log file (if it generates one)?

**Comment by rpontes343** [comment]
Yeah i checked the log and it loaded just fine, i guess the issue is i kept playing the first cutscenes and didn't realized they are pre-rendered that's why the fps was still locked at 30. I played further and there are now cutscenes rendering at 60 fps. Thanks!
