### ISSUE TITLE
cutscenes still at 30fps

### ISSUE THREAD

**Issue by gibbygundam** [Lyall/IshinFix#19]
Sorry if I've missed something obvious but the first cutscene when I start a new game is still at 30fps. I do have it on max settings with an i7-11700 11th gen 2.50 ghz, and an RTX 3060 Ti. Not sure if I'm pushing my pc too much, but the fps at the new game screen is around 215fps, and then when I load into the cutscene it jumps to 800+fps, then plummets to 30fps. 

![image](https://github.com/Lyall/IshinFix/assets/168246925/daf88c21-1480-49cb-a551-5493529e71e2)
![image](https://github.com/Lyall/IshinFix/assets/168246925/f7903c46-fe55-4ef3-bc1b-747e706d0da2)

**Comment by gibbygundam** [comment]
i also tried running it with lower settings but it still capped at 30

**Comment by Lyall** [comment]
This might be a silly question but the game actually starts with an FMV. Are you sure what you're seeing is an in-engine cutscene?

**Comment by gibbygundam** [comment]
ah that might be it. does that mean we're all stuck with 30fps story cutscenes throughout the game?

**Comment by Lyall** [comment]
Well for in-engine stuff it'll be unlocked but pre-rendered video (like the opening) will run at 30fps to match the video. You'd need to look at stuff like AI-upscaling videos and then modding them back in or something to address that.
