### ISSUE TITLE
brothel mini game bug

### ISSUE THREAD

**Issue by jeezany** [Lyall/IshinFix#4]
Hello,

First I want to thank you for your great work on this project.

I have faced an issue with the brothel mini game where I am not able to see the words and some other graphical bugs.
Below you can find my playthough showing the bug.
https://clips.twitch.tv/AgreeableBraveStingrayChocolateRain-2GNFVwC6ld_7d1xX

I think it this is the intender look of the mini game.
https://youtu.be/1IngAFtF8CM

It might be related to the aspect ratio modification.

**Comment by Lyall** [comment]
At first glance it looks like maybe the background texture of the girl is being stretched to fill the screen so I suspect your assumption of it being linked to aspect ratio is correct. 

Can you upload a save game so I can have a closer look? They should be located in `%APPDATA%\SEGA\LikeADragonIshin\<user-id>\`  according to PCGW. Otherwise you'd have to bear with me until I can get to a point in the game where I can access that minigame.

**Comment by jeezany** [comment]
Hello,

 I have attached the save file. you will find the brothel Infront of you.

[save0001.zip](https://github.com/Lyall/IshinFix/files/10825061/save0001.zip)

**Comment by Lyall** [comment]
Okay I've done some extensive testing now and come to the conclusion that it's a bug with the game. Even without IshinFix installed, if you are running at a resolution wider than 16:9 then the sensual healing minigame has bugged visuals. 

I am hesitant to look any further at the issue given the game has an upcoming patch to address UI elements appearing off screen on ultrawide displays. I suspect that it could be related to this issue and possibly even addressed in this patch. Adding to that, getting to the minigame in question is a pain so it makes testing quite arduous.

On the bright side, I am now an expert at rock, paper, scissors.

**Comment by jeezany** [comment]
I see. let us wait for the patch then.

for the rock, paper, scissors part of the mini game. try to look at her hand during the match as it will change based on what she will pick.

**Comment by Lyall** [comment]
I've added this issue to the known issues list just so people don't report the same issue. For now I'm going to close this issue as it's a bug with the game that is unrelated to IshinFix. I will however look in to the issue again after the upcoming game patch. If it does not address the bug then I will see if I can fix it and add it to IshinFix.
