### ISSUE TITLE
DllMain leaks a thread handle

### ISSUE THREAD

**Issue by CookiePLMonster** [Lyall/IshinFix#5]
For completeness, the handle returned by `CreateThread` should be closed, so the thread doesn't stick around. It's not an issue at this scope at all, but since it can be fixed with one success check and one call, no reason not to do it either.

**Comment by Lyall** [comment]
Totally worth fixing as you say. Am I right in thinking something as simple as this would be sufficient?

```c++
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    {
        CreateThread(NULL, 0, Main, 0, NULL, 0);

        if (Main)
        {
            CloseHandle(Main);
        }
    }
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```

You'll have to forgive me, I'm still quite the novice when it comes to C++.

**Comment by CookiePLMonster** [comment]
`Main` is not a handle so it needs to be something like
```cpp
        HANDLE handle = CreateThread(NULL, 0, Main, 0, NULL, 0);

        if (handle != nullptr)
        {
            CloseHandle(handle);
        }
        ```

**Comment by Lyall** [comment]
Awesome, I'll add this to the next version.

```c++
    case DLL_PROCESS_ATTACH:
    {
        HANDLE mainHandle = CreateThread(NULL, 0, Main, 0, NULL, 0);

        if (mainHandle != nullptr)
        {
            CloseHandle(mainHandle);
        }
    }
```

**Comment by Lyall** [comment]
That's it applied in the latest release. Thank you again for the report and letting me know how to fix it.
