### ISSUE TITLE
Fails to load .ini config file in MS Store version

### ISSUE THREAD

**Issue by TuxoYKT** [Lyall/IshinFix#6]
IshinFix expects the config file to be read from "Win64" folder, while **MS Store** version uses "WinGDK" folder for its binaries.
[IshinFix.log](https://github.com/Lyall/IshinFix/files/10826175/IshinFix.log)

**Comment by TuxoYKT** [comment]
Was able to compile IshinFix with different config path to "WinGDK" and the config can be read with no issues. Tested all the available options and here are some of the results.

- Fix Aspect Ratio (crashes after applying the LetterBox hook)
- Fix FOV (fails at pattern scan for FOV Culling, no crash)
- Remove Cutscene FPS Cap (works)
- Override Controller Icons (works)

**Comment by Lyall** [comment]
Nice work, this is good to know. Can you upload the main shipping executable for the MS Store version? Or is it locked down due permission issues? 

I already detect the executable name and path, I could add a check for the MS Store version based on that and change config path accordingly. With regards to the patterns failing, I'd need to see the exe to compare. It's possible that the offsets would be completely different and supporting that would mean different versions of each fix.

**Comment by TuxoYKT** [comment]
I can access the game files without any issues. I can send you the necessary files you need, but not sure if it's okay uploading these here. Any suggestions on how to and where to upload them with no problems?

**Comment by TuxoYKT** [comment]
I've dumped the main shipping executable using [UWPDumper](https://github.com/Wunkolo/UWPDumper). Can't seem to find any good places to upload it and send it to you.

**Comment by Lyall** [comment]
[PixelDrain](https://pixeldrain.com/) is a good quick and easy place to upload stuff. I doubt there's much risk in uploading given the exe contains Denuvo. No one could really do anything with it beyond looking at it forensically.

**Comment by TuxoYKT** [comment]
PixelDrain upload speeds were too low, and it would take hours to upload. I was able to upload it into [Discord](https://cdn.discordapp.com/attachments/864255434097426506/1078764710494744586/LikeaDragonIshin-WinGDK-Shipping.zip) with no issues.

**Comment by Lyall** [comment]
Okay, going to take a look at it and compare just now. I'll update this post further.

- **Letterbox fix**: The registers are different, would need to have an alternate fix for that one or rework the current solution.
- **Current resolution**: One value is different, could possibly change this to accommodate as the hook location was not too important.
-  **Aspect/FOV**: Looks the same, all good.

**Comment by Lyall** [comment]
Okay after a fair bit of work I have hopefully adapted it so that it can be used on the Microsoft Store version. Give this release a try and let me know how it goes. A log file would be much appreciated.

[IshinFix_v1_0_4_test.zip](https://github.com/Lyall/IshinFix/files/10829953/IshinFix_v1_0_4_test.zip)

**Comment by TuxoYKT** [comment]
Still crashes if you apply Aspect Ratio fix.
[IshinFix.log](https://github.com/Lyall/IshinFix/files/10830195/IshinFix.log)

**Comment by Lyall** [comment]
Looks like the register that has the address for the border objects was incorrect, it's r15 in the MS Store version. Give this a try.

[IshinFix_v1_0_4_test2.zip](https://github.com/Lyall/IshinFix/files/10831147/IshinFix_v1_0_4_test2.zip)

**Comment by TuxoYKT** [comment]
![image](https://user-images.githubusercontent.com/6498761/221357908-4fa88642-960f-441d-ac06-281f68ca011f.png)

Now it doesn't crash and seems to be working fine.

**Comment by Lyall** [comment]
Excellent. I know it's a bit of a favour to ask but can you try enabling all the features in the ini and just checking that they work? I'm fairly sure they should but without having the game, I cannot verify myself.

**Comment by TuxoYKT** [comment]
All the options works fine including the **Fix FOV**. However, I can't seem to make **AdditionalFOV** option to work. I tried changing values and saw no changes.

**Comment by Lyall** [comment]
Looks like I forgot to add back in the additional FOV functionality when I switched the FOV method. I have added that functionality back.

Thanks for verifying that it all works on the MS Store version now. I think it's probably good enough now to push in the next release.

**Comment by TuxoYKT** [comment]
I want to say thanks for allowing the people who bought the MS Store version to have those fixes.
