### ISSUE TITLE
Steam Deck

### ISSUE THREAD

**Issue by sergidiazlopez** [Lyall/IshinFix#8]
I wanted to inform that this mod works OK on the Steam Deck.

However, one extra step is needed for the game to load the DLL file under Proton. Writing the following in the Steam game launch options: `WINEDLLOVERRIDES="winmm.dll=n,b" %command%`

It would nice to add this to the readme.

**Comment by Lyall** [comment]
Thanks for reporting this! It has been added to the readme. I had meant to do it earlier but hadn't gotten around to verifying that it worked with my Steam Deck.
